# Configuration and calibration file for Motorroller

[general]
minimum_delay = 0.002 # this slows down the movement. recommended value: 0.002

# calibration point format [mm, ADC value]

[mot0]
limit_outside = 30
limit_inside = 70
cal_points = [[90, 869], [10, 3049]]

[mot1]
limit_outside = 30
limit_inside = 70
cal_points = [[90, 857], [10, 3047]]

[mot2]
limit_outside = 30
limit_inside = 70
cal_points = [[90, 831], [10, 3011]]

[mot3]
limit_outside = 30
limit_inside = 70
cal_points = [[90, 877], [10, 3039]]