# Config and calibration file for motors

# Value entry for every motor
[mot0]
# Absolute minimum and maximum in mm
limit_outside = 40
limit_inside = 60
# calibration points, use either floats or ints
cal_points = [[60, 1680], [46.5, 2058.0]]

# Value entry for every motor
[mot1]
# Absolute minimum and maximum in mm
limit_outside = 40
limit_inside = 60
# calibration points, use either floats or ints
cal_points = [[60, 1680], [46.5, 2058.0]]

# Value entry for every motor
[mot2]
# Absolute minimum and maximum in mm
limit_outside = 40
limit_inside = 60
# calibration points, use either floats or ints
cal_points = [[60, 1680], [46.5, 2058.0]]

# Value entry for every motor
[mot3]
# Absolute minimum and maximum in mm
limit_outside = 40
limit_inside = 60
# calibration points, use either floats or ints
cal_points = [[60, 1680], [46.5, 2058.0]]
